---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  labels:
    name: node-js-deploy
    app: node app
spec:
  type: loadbalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
  selector:
    name: node-js-deploy
    app: node app
