---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  labels:
    name: node-js-deploy
    app: nodeapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30011
  selector:
    name: node-js-deploy
    app: nodeapp
